function FunDy = systemOdeJacOrig(in1)
%SYSTEMODEJACORIG
%    FUNDY = SYSTEMODEJACORIG(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    10-Apr-2018 11:14:09

L = in1(:,4);
c = in1(:,3);
g = in1(:,5);
k = in1(:,2);
m = in1(:,1);
t2 = 1.0./m;
t3 = 1.0./L;
t4 = g.*m.*3.0;
FunDy = reshape([0.0,0.0,0.0,k.*t2.*t3.*-3.0,0.0,0.0,t2.*(t4+L.*k.*2.0).*(1.0./3.0),-t2.*t3.*(t4+L.*k.*4.0),1.0,0.0,c.*t2.*(-1.0./3.0),-c.*t2.*t3,0.0,1.0,L.*c.*t2.*(1.0./3.0),c.*t2.*-2.0],[4,4]);
